AdminBundle\Entity\epizy_demandeur_experience:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\epizy_demandeur_experienceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        moisDebut:
            type: string
            length: 255
            column: mois_debut
        moisFin:
            type: string
            length: 255
            column: mois_fin
        annee:
            type: integer
        ville:
            type: string
            length: 255
        villeId:
            type: integer
            column: ville_id
        pays:
            type: string
            length: 255
        nomEntreprise:
            type: string
            length: 255
            column: nom_entreprise
        secteurActivite:
            type: string
            length: 255
            column: secteur_activite
        posteOccupe:
            type: string
            length: 255
            column: poste_occupe
        missionTache:
            type: text
            column: mission_tache
    lifecycleCallbacks: {  }

    manyToOne:
        id_demandeur:
            targetEntity: epizy_demandeur_emplois
            joinColumn:
                name: id_demandeur
                referencedColumnName: id
                onDelete: SET NULL
        id_cv:
            targetEntity: epizy_demandeur_cvs
            inversedBy: experience
            joinColumn:
                name: id_cv
                referencedColumnName: id
                onDelete: SET NULL
        posteoccupe_id:
            targetEntity: epizy_poste_occupes
            joinColumn:
                name: posteoccupe_id
                referencedColumnName: id
                onDelete: SET NULL
        secteuractivite_id:
            targetEntity: epizy_secteur_activites
            joinColumn:
                name: secteuractivite_id
                referencedColumnName: id
                onDelete: SET NULL
