AdminBundle\Entity\epizy_demandeur_cvs:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\epizy_demandeur_cvsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        permis:
            type: string
            length: 255
        emploiRecherche:
            type: string
            length: 255
            column: emploi_recherche
        logiciel:
            type: string
            length: 255
        langue:
            type: string
            length: 255
        statu:
            type: integer
        reference:
            type: string
            length: 255
        centreInteretCertificat:
            type: string
            length: 255
            column: centre_interet_certificat
        certificationId:
            type: integer
            column: certification_id
        centreInteretProjet:
            type: string
            length: 255
            column: centre_interet_projet
        dateCreation:
            type: datetime
            column: date_creation
        datePublished:
            type: datetime
            nullable: true
            column: date_published
        nbrVue:
            type: integer
            column: nbr_vue
        position:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        id_demandeur:
            targetEntity: epizy_demandeur_emplois
            joinColumn:
                name: id_demandeur
                referencedColumnName: id
        logiciel_id:
            targetEntity: epizy_logiciels
            inversedBy: demandeur_cvs
            joinColumn:
                name: logiciel_id
                referencedColumnName: id
                cascade: [ persist ]
        langue_id:
            targetEntity: epizy_langues
            joinColumn:
                name: langue_id
                referencedColumnName: id
        emploirecherche_id:
            targetEntity: epizy_emploi_recherches
            inversedBy: cvs_id
            joinColumn:
                name: emploirecherche_id
                referencedColumnName: id
    OneToMany:
        experience:
            targetEntity: epizy_demandeur_experience
            mappedBy: id_cv