AdminBundle\Entity\epizy_demandeur_formations:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\epizy_demandeur_formationsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        annee:
            type: string
            length: 255
        ville:
            type: string
            length: 255
        villeId:
            type: integer
            column: ville_id
        pays:
            type: string
            length: 255
        diplome:
            type: string
            length: 255
        diplomeId:
            type: integer
            column: diplome_id
        universite:
            type: string
            length: 255
        universiteId:
            type: integer
            column: universite_id
    lifecycleCallbacks: {  }

    manyToOne:
        id_demandeur:
            targetEntity: epizy_demandeur_emplois
            joinColumn:
                name: id_demandeur
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
        id_cvs:
            targetEntity: epizy_demandeur_cvs
            inversedBy: formation
            joinColumn:
                name: id_cvs
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL