AdminBundle\Entity\epizy_emploi_recherches:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\epizy_emploi_recherchesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libele:
            type: string
            length: 255
        etat:
            type: string
            length: 255
        created:
            type: datetime
    lifecycleCallbacks: {  }
    oneToMany:
        cvs_id:
            targetEntity: epizy_demandeur_cvs
            mappedBy : emploirecherche_id